data:
  annot_ext: .txt
  data_dir: /home/automatedtomato/github.com/automatedtomato/sar-yolo/sar_dataset
  img_ext: .png
  source: file
  test:
    annot_path: data/new_dataset3/test/labels
    img_path: data/new_dataset3/test/images
  train:
    annot_path: data/new_dataset3/train/labels
    img_path: data/new_dataset3/train/images
  val:
    annot_path: data/new_dataset3/val/labels
    img_path: data/new_dataset3/val/images
dataloader:
  batch_size: 8
  num_workers: 4
  pin_memory: true
evaluating:
  conf_threshold: 0.5
  fig_path: figures/006_lr.png
  iou_threshold: 0.5
  metrics_path: ../metrics/006_metrics.csv
  nms_threshold: 0.5
loss:
  lambda_class: 1.0
  lambda_coord: 5.0
  lambda_noobj: 0.5
  lambda_obj: 1.0
  obj_threshold: 0.5
model:
  anchors:
  - - - 37.0
      - 24.0
    - - 29.0
      - 50.0
    - - 55.0
      - 30.0
  - - - 11.0
      - 22.0
    - - 24.0
      - 17.0
    - - 19.0
      - 33.0
  - - - 4.0
      - 5.0
    - - 7.0
      - 12.0
    - - 15.0
      - 11.0
  grid_sizes:
  - 13
  - 26
  - 52
  input_size: 480
  n_classes: 0
  name: yolov3_sample_006
optimizer:
  lr: 0.001
  type: adam
  weight_decay: 0.0005
scheduler:
  type: lambda
training:
  accumulation_steps: 1
  log_interval: 10
  n_epochs: 5
  patience: 10
  save_path: 006_best_model.pt
