data:
  annot_ext: .txt
  bucket_name: sar-dataset
  img_ext: .png
  test:
    annot_path: data/new_dataset3/test/labels
    img_path: data/new_dataset3/test/images
  train:
    annot_path: data/new_dataset3/train/labels
    img_path: data/new_dataset3/train/images
  val:
    annot_path: data/new_dataset3/val/labels
    img_path: data/new_dataset3/val/images
dataloader:
  batch_size: 16
  num_workers: 4
  pin_memory: true
experimets:
  log_interval: 100
  name: yolov3_experiment_001
  save_dir: ./experiments/
loss:
  lambda_class: 1.0
  lambda_coord: 5.0
  lambda_noobj: 0.5
  lambda_obj: 1.0
  obj_threshold: 0.5
model:
  anchors:
  - - - 38.0
      - 25.0
    - - 29.0
      - 50.0
    - - 56.0
      - 30.0
  - - - 11.0
      - 22.0
    - - 25.0
      - 18.0
    - - 18.0
      - 33.0
  - - - 4.0
      - 5.0
    - - 7.0
      - 12.0
    - - 15.0
      - 12.0
  grid_sizes:
  - 13
  - 26
  - 52
  input_size: 416
  n_classes: 1
optimizer:
  lr: 0.001
  type: adam
  weight_decay: 0.0005
training:
  log_interval: 16
  n_epochs: 10
  patience: null
  save_path: 001_sample_best_model.pt
